# Generated by Django 4.2.4 on 2023-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediaTitle', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mediaSource', models.CharField(max_length=100)),
                ('mediaType', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
